resource "yandex_iam_service_account" "bootstrap" {
  folder_id   = yandex_resourcemanager_folder.platform.id
  name        = "bootstrap"
  description = "Bootstrap / platform structure administration"
}

resource "yandex_resourcemanager_cloud_iam_member" "bootstrap_resource_manager" {
  cloud_id = local.cloud_id
  role     = "resource-manager.admin"
  member   = "serviceAccount:${yandex_iam_service_account.bootstrap.id}"
}

resource "yandex_resourcemanager_folder_iam_member" "bootstrap_storage_editor" {
  folder_id = yandex_resourcemanager_folder.platform.id
  role      = "storage.editor"
  member    = "serviceAccount:${yandex_iam_service_account.bootstrap.id}"
}

resource "yandex_iam_service_account" "tfstate" {
  folder_id   = yandex_resourcemanager_folder.platform.id
  name        = "tfstate"
  description = "Object Storage access for Terraform remote state"
}

resource "yandex_resourcemanager_folder_iam_member" "tfstate_storage_editor" {
  folder_id = yandex_resourcemanager_folder.platform.id
  role      = "storage.editor"
  member    = "serviceAccount:${yandex_iam_service_account.tfstate.id}"
}

resource "yandex_iam_service_account_static_access_key" "tfstate" {
  service_account_id = yandex_iam_service_account.tfstate.id
  description        = "Static keys for Terraform S3-compatible backend"
}

resource "yandex_iam_service_account" "terraform_env" {
  for_each = local.env_folders

  folder_id   = each.value.id
  name        = "terraform-${each.key}"
  description = "Terraform automation for ${each.key} folder"
}

resource "yandex_resourcemanager_folder_iam_member" "terraform_env_editor" {
  for_each = local.env_folders

  folder_id = each.value.id
  role      = "editor"
  member    = "serviceAccount:${yandex_iam_service_account.terraform_env[each.key].id}"
}

resource "local_sensitive_file" "backend_credentials" {
  count = var.write_backend_credentials ? 1 : 0

  filename        = var.backend_credentials_path
  file_permission = "0600"
  content         = <<-EOT
    # Generated by terraform-yc-bootstrap — do not commit
    # Docker / Compose env-file format (KEY=VALUE). Do not bash `source` this file.
    AWS_ACCESS_KEY_ID=${yandex_iam_service_account_static_access_key.tfstate.access_key}
    AWS_SECRET_ACCESS_KEY=${yandex_iam_service_account_static_access_key.tfstate.secret_key}
  EOT
}
