# Shared helpers for bootstrap / join (BusyBox wget + IAM Bearer; no curl/jq/yc in image).
# shellcheck shell=bash

WORKSPACE_META_KEY="${WORKSPACE_META_KEY:-bootstrap/workspace.json}"
STORAGE_S3_ENDPOINT="${STORAGE_S3_ENDPOINT:-https://storage.yandexcloud.net}"
ORG_API="${ORG_API:-https://organization-manager.api.cloud.yandex.net/organization-manager/v1}"
RM_API="${RM_API:-https://resource-manager.api.cloud.yandex.net/resource-manager/v1}"
STORAGE_API="${STORAGE_API:-https://storage.api.cloud.yandex.net/storage/v1}"
IAM_AWS_API="${IAM_AWS_API:-https://iam.api.cloud.yandex.net/iam/aws-compatibility/v1}"

yc_bearer() {
  if [[ -n "${YC_TOKEN:-}" ]]; then
    printf '%s' "$YC_TOKEN"
    return 0
  fi
  die "YC_TOKEN is required for Yandex API calls (join/discovery). SA key file alone is not enough for wget/API helpers."
}

# GET URL with Bearer token → stdout. Uses BusyBox wget.
yc_http_get() {
  local url="$1"
  local tmp
  tmp="$(mktemp)"
  if ! wget -q -O "$tmp" --header "Authorization: Bearer $(yc_bearer)" "$url"; then
    rm -f "$tmp"
    return 1
  fi
  cat "$tmp"
  rm -f "$tmp"
}

# Extract first JSON string value for a top-level-ish key: "key": "value"
json_str() {
  local json="$1" key="$2"
  printf '%s' "$json" | sed -n "s/.*\"${key}\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p" | head -1
}

write_backend_files() {
  local bucket="$1" key="$2"
  ensure_backend_tf
  write_backend_hcl "$bucket" "$key"
}

write_workspace_hint_env() {
  local cloud_id="$1"
  local path="${WORKSPACE_HINT_ENV:-.workspace.env}"
  cat >"$path" <<EOF
# Generated by join/attach — optional; source or merge into .env
# Do not commit
TF_VAR_cloud_id=${cloud_id}
EOF
  log "Wrote ${path} (TF_VAR_cloud_id for reuse)"
}

write_backend_credentials_file() {
  local access="$1" secret="$2"
  local path="${BACKEND_CREDENTIALS_FILE:-.backend-credentials}"
  cat >"$path" <<EOF
# Generated by join/attach — do not commit
AWS_ACCESS_KEY_ID=${access}
AWS_SECRET_ACCESS_KEY=${secret}
EOF
  chmod 600 "$path" 2>/dev/null || true
  AWS_ACCESS_KEY_ID="$access"
  AWS_SECRET_ACCESS_KEY="$secret"
  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
  log "Wrote ${path}"
}

mint_tfstate_access_key() {
  local sa_id="$1"
  local body resp access secret
  body="{\"serviceAccountId\":\"${sa_id}\",\"description\":\"terraform-yc-bootstrap join $(date -u +%Y%m%dT%H%M%SZ)\"}"
  local tmp
  tmp="$(mktemp)"
  if ! wget -q -O "$tmp" \
    --header "Authorization: Bearer $(yc_bearer)" \
    --header "Content-Type: application/json" \
    --post-data "$body" \
    "${IAM_AWS_API}/accessKeys"; then
    rm -f "$tmp"
    die "failed to create static access key for SA ${sa_id} (need iam permission to create access keys, or set AWS_* in .env)"
  fi
  resp="$(cat "$tmp")"
  rm -f "$tmp"
  access="$(json_str "$resp" keyId)"
  [[ -n "$access" ]] || access="$(json_str "$resp" accessKeyId)"
  # Response shape: accessKey.keyId + secret
  if [[ -z "$access" ]]; then
    access="$(printf '%s' "$resp" | sed -n 's/.*"keyId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
  fi
  secret="$(json_str "$resp" secret)"
  [[ -n "$access" && -n "$secret" ]] || die "IAM accessKeys response missing keyId/secret: ${resp:0:200}"
  write_backend_credentials_file "$access" "$secret"
}

ensure_aws_creds_for_attach() {
  local sa_id="$1"
  if [[ -n "${AWS_ACCESS_KEY_ID:-}" && -n "${AWS_SECRET_ACCESS_KEY:-}" ]]; then
    return 0
  fi
  if load_aws_creds_from_file; then
    log "Loaded AWS credentials from ${BACKEND_CREDENTIALS_FILE:-.backend-credentials}"
    return 0
  fi
  log "Minting new static access key for tfstate SA ${sa_id}"
  mint_tfstate_access_key "$sa_id"
}

fetch_workspace_meta() {
  local bucket="$1"
  local url="${STORAGE_S3_ENDPOINT}/${bucket}/${WORKSPACE_META_KEY}"
  local body
  body="$(yc_http_get "$url")" || return 1
  printf '%s' "$body" | grep -q '"schema_version"' || return 1
  printf '%s' "$body"
}

# List bucket names in a folder (JSON array of name fields).
list_bucket_names_in_folder() {
  local folder_id="$1"
  local body
  body="$(yc_http_get "${STORAGE_API}/buckets?folderId=${folder_id}")" || return 1
  printf '%s' "$body" | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
}

list_platform_folder_ids_in_cloud() {
  local cloud_id="$1"
  local body
  body="$(yc_http_get "${RM_API}/folders?cloudId=${cloud_id}")" || return 1
  # Prefer folders named platform (default); also match any folder that has our meta later.
  printf '%s' "$body" | awk '
    /"id"/ { id=$0; sub(/.*"id"[[:space:]]*:[[:space:]]*"/,"",id); sub(/".*/,"",id) }
    /"name"/ {
      name=$0; sub(/.*"name"[[:space:]]*:[[:space:]]*"/,"",name); sub(/".*/,"",name)
      if (name == "platform") print id
    }
  '
}

list_cloud_ids() {
  local org="${TF_VAR_organization_id:-}"
  local body cloud
  if [[ -n "${TF_VAR_cloud_id:-}" ]]; then
    printf '%s\n' "$TF_VAR_cloud_id"
    return 0
  fi
  if [[ -n "$org" ]]; then
    body="$(yc_http_get "${RM_API}/clouds?organizationId=${org}")" || return 1
    printf '%s' "$body" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
    return 0
  fi
  # No org/cloud in env: list organizations visible to the token, then clouds in each.
  body="$(yc_http_get "${ORG_API}/organizations")" || return 1
  local orgs
  orgs="$(printf '%s' "$body" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
  [[ -n "$orgs" ]] || return 1
  while IFS= read -r org; do
    [[ -z "$org" ]] && continue
    body="$(yc_http_get "${RM_API}/clouds?organizationId=${org}")" || continue
    printf '%s' "$body" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
  done <<<"$orgs"
  return 0
}

# Prints candidate bucket names that contain workspace meta (one per line).
# Returns 1 if none found. Dies if many (or TFSTATE_BUCKET invalid).
discover_workspace_buckets() {
  local cloud folder bucket
  if [[ -n "${TFSTATE_BUCKET:-}" ]]; then
    if fetch_workspace_meta "$TFSTATE_BUCKET" >/dev/null; then
      printf '%s\n' "$TFSTATE_BUCKET"
      return 0
    fi
    die "TFSTATE_BUCKET=${TFSTATE_BUCKET} has no readable ${WORKSPACE_META_KEY}"
  fi

  local clouds
  if ! clouds="$(list_cloud_ids)"; then
    return 1
  fi
  [[ -n "$(printf '%s' "$clouds" | sed '/^$/d')" ]] || return 1

  local found_file
  found_file="$(mktemp)"
  while IFS= read -r cloud; do
    [[ -z "$cloud" ]] && continue
    while IFS= read -r folder; do
      [[ -z "$folder" ]] && continue
      while IFS= read -r bucket; do
        [[ -z "$bucket" ]] && continue
        if fetch_workspace_meta "$bucket" >/dev/null 2>&1; then
          printf '%s\n' "$bucket" >>"$found_file"
        fi
      done < <(list_bucket_names_in_folder "$folder" 2>/dev/null || true)
    done < <(list_platform_folder_ids_in_cloud "$cloud" 2>/dev/null || true)
  done <<<"$clouds"

  local count
  count="$(sed '/^$/d' "$found_file" | wc -l | tr -d ' ')"
  if [[ "$count" -eq 0 ]]; then
    rm -f "$found_file"
    return 1
  fi
  if [[ "$count" -gt 1 ]]; then
    local list
    list="$(cat "$found_file")"
    rm -f "$found_file"
    die "multiple workspaces found:
${list}
Set TFSTATE_BUCKET to disambiguate"
  fi
  cat "$found_file"
  rm -f "$found_file"
  return 0
}

# Attach to remote workspace: backend files, creds, terraform init. Returns 0 on success.
attach_workspace() {
  local mode="${1:-attach}" # attach | require
  local buckets bucket meta state_key sa_id cloud_id count

  if ! buckets="$(discover_workspace_buckets)"; then
    [[ "$mode" == "require" ]] && die "no workspace meta found (run bootstrap create first, or set TFSTATE_BUCKET / TF_VAR_cloud_id / TF_VAR_organization_id)"
    return 1
  fi
  count="$(printf '%s\n' "$buckets" | sed '/^$/d' | wc -l | tr -d ' ')"
  if [[ "$count" -gt 1 ]]; then
    die "multiple workspaces found:
${buckets}
Set TFSTATE_BUCKET to disambiguate"
  fi
  bucket="$(printf '%s\n' "$buckets" | sed '/^$/d' | head -1)"
  log "Attaching to workspace bucket ${bucket}"

  meta="$(fetch_workspace_meta "$bucket")" || die "failed to fetch ${WORKSPACE_META_KEY} from ${bucket}"
  state_key="$(json_str "$meta" state_key)"
  sa_id="$(json_str "$meta" tfstate_service_account_id)"
  cloud_id="$(json_str "$meta" cloud_id)"
  [[ -n "$state_key" ]] || state_key="bootstrap/terraform.tfstate"
  [[ -n "$sa_id" ]] || die "meta missing tfstate_service_account_id"
  [[ -n "$cloud_id" ]] || die "meta missing cloud_id"

  write_backend_files "$bucket" "$state_key"
  write_workspace_hint_env "$cloud_id"
  ensure_aws_creds_for_attach "$sa_id"

  log "terraform init (remote)"
  terraform init -input=false -backend-config="$BACKEND_HCL"
  ATTACH_BUCKET="$bucket"
  export ATTACH_BUCKET
  return 0
}
